### ISSUE TITLE
ocrd_calamari PAGE-XML output not valid PAGE-XML?

### ISSUE THREAD

**Issue by cneud** [OCR-D/ocrd_calamari#11]
It appears the PAGE-XML output produced by ``ocrd_calamari`` is not valid PAGE-XML - at least the files do not open in [Aletheia](https://www.primaresearch.org/tools/Aletheia), the PRImA official tool for working with PAGE-XML files (tested with [this](https://gist.github.com/cneud/522928b25322a9ab18d8dfc8c9100e00#file-ocrd_calamari_page-xml) output file from ``ocrd_calamari`` and Aletheia v4.0.

**Comment by mikegerber** [comment]
The file validates using `xmllint` and opens in PAGE Viewer, so my hunch is that Aletheia v4.0 does not support PAGE 2019 yet?

~~~
% xmllint -schema pagecontent.xsd --noout ocrd_calamari_PAGE.xml
ocrd_calamari_PAGE.xml validates
~~~

**Comment by cneud** [comment]
> my hunch is that Aletheia v4.0 does not support PAGE 2019 yet?

Good point, let me confirm that with @chris1010010

**Comment by cneud** [comment]
..and confirmed already! Aletheia 4.1 will add support for PAGE 2019 and is due for release in a few days/weeks.
