### ISSUE TITLE
Include alternative predictions

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_calamari#28]
Calamari provides alternative predictions for characters. These should be included in the PAGE output.

See also #17 (extended prediction data) and #9 (results below line level)

**Comment by mikegerber** [comment]
Experiments look promising.

![image](https://user-images.githubusercontent.com/34309482/73472559-86d76680-438b-11ea-9a64-721dd93401fb.png)

This is just a fancy plot of the results from this code snippet:
~~~
raw_results = list(predictor.predict_raw([image], progress_bar=False))[0]
voted_prediction = voter.vote_prediction_result(raw_results)
~~~

**Comment by mikegerber** [comment]
AFAICT, PAGE-XML does not allow including character segmentation without word segmentation, so word segmentation must be created for this, too.

**Comment by kba** [comment]
Yes, hierarchies are strict in PAGE. *Region, TextLine, Word, Glyph

**Comment by mikegerber** [comment]
![image](https://user-images.githubusercontent.com/34309482/73543698-d3787b80-4437-11ea-91ba-3f885ad143f8.png)

Word segmentation inferred from Unicode text segmentation, this should suffice for now.

**Comment by mikegerber** [comment]
master now contains preliminary support for this, here is an example Glyph:

~~~
                    <pc:Glyph id="l1_word0000_glyph0001">
                        <pc:Coords points="391,258 407,258 407,305 391,305"/>
                        <pc:TextEquiv index="0" conf="0.9252094626426697">
                            <pc:Unicode>0</pc:Unicode>
                        </pc:TextEquiv>
                        <pc:TextEquiv index="1" conf="0.07439321279525757">
                            <pc:Unicode>O</pc:Unicode>
                        </pc:TextEquiv>
                        <pc:TextEquiv index="3" conf="0.0006183699006214738">
                            <pc:Unicode>o</pc:Unicode>
                        </pc:TextEquiv>
                        <pc:TextEquiv index="4" conf="0.0004007623065263033">
                            <pc:Unicode>D</pc:Unicode>
                        </pc:TextEquiv>
                        <pc:TextEquiv index="5" conf="0.0001221101265400648">
                            <pc:Unicode>ο</pc:Unicode>
                        </pc:TextEquiv>
                        <pc:TextEquiv index="6" conf="7.388382073258981e-05">
                            <pc:Unicode>6</pc:Unicode>
                        </pc:TextEquiv>
                        <pc:TextEquiv index="7" conf="2.814948675222695e-05">
                            <pc:Unicode>G</pc:Unicode>
                        </pc:TextEquiv>
                    </pc:Glyph>
~~~

**Comment by mikegerber** [comment]
The word segmentation is not as the OCR-D validator expects it (interpunction seems to be expected as part of words), but I'm going to close this now and revisit the word segmentation when https://github.com/OCR-D/core/issues/430 is fixed.
