### ISSUE TITLE
Add parameter to control output granularity below textline

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_calamari#31]
`ocrd-calamari-recognize` now supports #9 (adding words and glyphs from the textline decoder results).

It would be favourable to allow controlling the level of segmentation detail to be added below line, as do `ocrd-tesserocr-recognize` and `ocrd-cis-ocropy-recognize` with `textequiv_level`:
- `line`: do _not_ add further segmentation (e.g. to save computation)
- `word`: add `Word` elements
- `glyph`: add `Word` and `Glyph` elements

NB: In the Tesseract wrapper, that parameter is also responsible for controlling the level of operation (_page segmentation mode_) if segmentation is already present at the lower levels. For example, with `textequiv_level=word`, if there are already `Word` elements below a `TextLine`, Tesseract only gets images cropped around these words and runs in `PSM.SINGLE_WORD` instead of `PSM.SINGLE_LINE`. IMHO there is no need/use in attempting something like this for engines that do not natively provide modes other than textline processing.

**Comment by mikegerber** [comment]
Fixed in https://github.com/OCR-D/ocrd_calamari/commit/ef3fb44fb528e9e52b78fe1e787e38142da7a7d4
