### ISSUE TITLE
Fix or disable Docker build

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_calamari#34]
Docker builds are failing, the "Details" link to a 404 error page.

![image](https://user-images.githubusercontent.com/34309482/73936452-2b552d80-48e3-11ea-8f45-72f022c2cf4f.png)

- [x] Fix the Docker build
- [x] Do not use calamari/build make target, we are using the version from PyPI
- ~~Check if this Docker build is useful (not using it personally)~~ (→ #36)
- [x] Fix the build on dockercloud?

**Comment by mikegerber** [comment]
- [ ] Fix the Docker build
- [ ] Do not use calamari/build make target, we are using the version from PyPI
- [ ] Check if this Docker build is useful (not using it personally)
- [ ] Fix the build on dockercloud?

**Comment by mikegerber** [comment]
Build was mostly fixed in https://github.com/OCR-D/ocrd_calamari/commit/1fda419f2585cbba099263b0545b7e61f8b9793a

**Comment by mikegerber** [comment]
Removed calamari/build (stick to pip) in https://github.com/OCR-D/ocrd_calamari/commit/a2d1d76dbdb0ca2207db31e67d6e7d7ce4c1c844

**Comment by kba** [comment]
Automatic builds are working again at https://hub.docker.com/r/ocrd/calamari

> Check if this Docker build is useful (not using it personally)

Me neither but that might change in the future. So unless it's masssive effort to support, let's keep the automatic build as-it-is.

> Fix the build on dockercloud?

Your setup fixes fixed the build. It automatically rebuilds master to `latest` on new commits.

**Comment by kba** [comment]
What's the problem? Looks like [it's building ok](https://hub.docker.com/r/ocrd/calamari/builds)?

**Comment by mikegerber** [comment]
I moved the remaining TODO to #36.
