### ISSUE TITLE
Include default Output format to Documentation

### ISSUE THREAD

**Issue by GrazingScientist** [OCR-D/ocrd_calamari#43]
The documentation should include a hint to the default outputformat to be PAGE-XML.

**Comment by mikegerber** [comment]
I've updated to [README](https://github.com/OCR-D/ocrd_calamari/blob/master/README.md)'s introduction with more info/links to OCR-D and PAGE XML:

> ocrd_calamari offers a OCR-D compliant workspace processor for the functionality of Calamari OCR. It uses PAGE XML documents as input and output.
