### ISSUE TITLE
Documentation: README completeness, debug ocrd-tool.json

### ISSUE THREAD

**Issue by tboenig** [OCR-D/ocrd_calamari#5]
Please debug your ocrd_tool.json file. 
I found  some errors:  
```xml
<report valid="false">
  <error>[tools.ocrd-calamari-recognize.parameters.checkpoint] 'description' is a required property</error>
  <error>[tools.ocrd-calamari-recognize.parameters.voter] 'description' is a required property</error>
</report>
```
You can find the ocrd-tool.json documentation: https://ocr-d.github.io/ocrd_tool

Please check your README file and complet them. An ideal README file look like:
 ```
# Name of application


## Introduction
...

## Installation
...

## Usage
...

## Testing
...
```
Thank you very much.

**Comment by mikegerber** [comment]
- [ ] Add descriptions for the parameters
- [ ] Review README.md

**Comment by mikegerber** [comment]
The parameter descriptions are now there (c4d52ee).

**Comment by mikegerber** [comment]
README.md now contains installation and testing instructions.
