### ISSUE TITLE
ocrd-calamari-recognize loses trained formatting characters

### ISSUE THREAD

**Issue by helkejaa** [OCR-D/ocrd_calamari#62]
I have a model trained to represent italics and bold face with opening and closing characters. Angular brackets for italics ´<´, ´>´ and curly brackets for bold face ´{´, ´}´. For example _this_  would be recognized as \<this\>. A similar case is for example https://github.com/poke1024/origami_models. Problems arise with lines where the line terminates with italics of bold face. In these cases the expected recognition results should include the closing character, `>` or `}`, before the line breaks, but these characters don't show up. For other positions this is not a problem. In line beginning and inside the line italics and bold face are succesfully recognized with the opening and closing characters. Further, this problem doesn't appear when using `calamari-predict` from calamari-ocr (with the same model). This calamari-ocr is the same used with the ocrd venv in question. That is, recognising the same files with `calamari-predict` gives correct closing characters at the end of the line.

@bertsky has suggested the reason for this behaviour in a conversation in OCRD [Lobby](https://gitter.im/OCR-D/Lobby?at=60441112a3a2f04f1fdaefe1), pointing to possible part of the [code](https://github.com/OCR-D/ocrd_calamari/blob/da98713e73b998b6c5a10e341c9e6e0af59d84de/ocrd_calamari/recognize.py#L147-L153).

`ocrd==2.23.0`
`calamari-ocr==1.0.5`
`ocrd_calamari==1.0.2`
`tensorflow==2.3.0`

I have used the same method previously without this problem, but perhaps with some other versions of calamari-ocr and ocrd_calamari.

**Comment by mikegerber** [comment]
I would gladly look into this, but without data (model and test files) I don't see how I could. Could you please upload a model and test data so I can reproduce?

It's not obvious to me that the code part mentioned would trigger this, but it _is_ the part of the code that has a potential different behaviour compared to upstream Calamari.

**Comment by helkejaa** [comment]
I made an example set. I included workflow which should produce nescessary files. [https://disk.yandex.com/d/CXEQAmd_vlMlRg](The set)


```
cat workflow.sh
ocrd workspace init
ocrd workspace set-id example_zulu
for i in OCR-D-IMG/*.tif ; do base=`basename ${i} .tif`; ocrd workspace add -G OCR-D-IMG -i OCR-D-IMG_${base} -g P_${base} -m image/tif ${i}; done
ocrd process \
	"cis-ocropy-binarize -I OCR-D-IMG -O OCR-D-BIN -P dpi 500" \
	"tesserocr-segment-region -I OCR-D-BIN -O OCR-D-SEG-REG -P find_tables false" \
	"cis-ocropy-segment -I OCR-D-SEG-REG -O OCR-D-SEG-LINE -P level-of-operation region -P dpi 500" \
	"cis-ocropy-dewarp -I OCR-D-SEG-LINE -O OCR-D-DEWARP-LINE -P dpi 500" \
	"calamari-recognize -I OCR-D-DEWARP-LINE -O OCR-D-CALAMARI -P checkpoint best_model/*.ckpt.json"
mkdir calamari_comparison
cp -v OCR-D-DEWARP-LINE/OCR-D-DEWARP-LINE*.png calamari_comparison/
calamari-predict --checkpoint best_model/*.ckpt.json --files calamari_comparison/*.png
python page2text.py OCR-D-CALAMARI/OCR-D-CALAMARI_zulu-100_1L.xml >ocrd_zulu-100_1L
python page2text.py OCR-D-CALAMARI/OCR-D-CALAMARI_zulu-610_1L.xml >ocrd_zulu-610_1L
awk '{print $0}' calamari_comparison/*100_1L*pred.txt >calamari_100_1L
awk '{print $0}' calamari_comparison/*610_1L*pred.txt >calamari_610_1L
```

**Comment by helkejaa** [comment]
I have abandoned this method for a better one as this does not seem to work that well. Thank you for your attention!

**Comment by kba** [comment]
> I have abandoned this method for a better one as this does not seem to work that well. Thank you for your attention!

Thanks for getting back on this, sorry to hear this didn't work for you. May I ask what method you're using instead?

**Comment by helkejaa** [comment]
The method I'm using is not that different from the previous. I got the idea from a conversation in the Lobby where someone mentioned that in the Kraken project a similar method to the one described here gave highly satisfying results. 

Instead of marking an area with opening and closing characters, I annotate every relevant character with an extra symbol. For example "normal **bold** normal" would be `normal {b{o{l{d normal`. For the practical side I actually still annotate gt files as `normal {bold} normal`, but after this I use script to place the formatting character before every character (a simple task with python `split` and `re.sub`). Converting the recognized output to a more readable and workable form is easy as well and in contrast to the previous method it's easier to correct possible recognition failures if the text has conditions for a text style (e.g. only complete words have a text style etc.). What I do not know is how well this method would work for models trained with multiple (in some features differentiating) documents. I have usually trained a new model for each project/book/document. I should perhaps mention that I have been using this with standalone Calamari-OCR 2.0.0, but I think it should work for ocrd-calamari as well.
