### ISSUE TITLE
Decide how to handle textline without text

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_calamari#63]
@kba showed us this `pc:TextLine` from an ocrd_calamari output:

~~~xml
<pc:TextLine id="l2">                                     
    <pc:Coords points="302,655 532,653 533,728 302,732"/> 
    <pc:TextEquiv conf="0.">                              
        <pc:Unicode></pc:Unicode>                         
    </pc:TextEquiv>                                       
</pc:TextLine>   
~~~

Because this raises the issue of how to handle this in a subsequent transformation to ALTO - which requires text - we should think about how to handle this.

Pro removing the line:
- No problem with ALTO

Con removing the line:
- The line disappears and users can't just compare layout detection output with OCR output (i.e. "In this line no text was detected")

I'm leaning towards keeping the line and let the ALTO conversion handle it. But I'll check if `ocrd workspace validate` considers a line with empty text valid output (I hope it does, I see no reason why it should be invalid).

@kba What are your thoughts on this?

**Comment by mikegerber** [comment]
`ocrd workspace validate` is OK with empty text.

**Comment by kba** [comment]
I do not think that this is a bug per se. Granted, it is suspicious that a line without text was detected. And you could ponder philosophically whether a text line without text is anything but whitespace. In all likelihood, it's a misdetection but I would still keep it. It is valid schema-wise AFAIK.

And as for https://github.com/kba/page-to-alto, I think the best way would be to make the behavior configurable: Either skip empty lines or write them out with an empty dummy word so the coordinates are retained.

**Comment by mikegerber** [comment]
> I do not think that this is a bug per se.

Agreed, it's an edge case.

> Granted, it is suspicious that a line without text was detected. And you could ponder philosophically whether a text line without text is anything but whitespace. In all likelihood, it's a misdetection but I would still keep it. It is valid schema-wise AFAIK.

Also agreed ;-) In addition to a misdetection it could also be a bad detection (i.e. bounding box incorrect) or that the OCR model just can't recognize the text in a perfectly good text line, due to the model or unknown script etc.

> And as for https://github.com/kba/page-to-alto, I think the best way would be to make the behavior configurable: Either skip empty lines or write them out with an empty dummy word so the coordinates are retained.

👍
