### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_calamari#66]
In a Python 3.9 venv:

~~~
% python --version                                                                                      master 
Python 3.9.5
% pip install -e .                                                                                          master 
Obtaining file:///home/mike/devel/ocrd_calamari
Collecting h5py<3
  Using cached h5py-2.10.0.tar.gz (301 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.5.0,>=2.3.0rc2 (from ocrd-calamari) (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.6.0rc0)
ERROR: No matching distribution found for tensorflow<2.5.0,>=2.3.0rc2
~~~

Related to #64 and possibly #61.

**Comment by bertsky** [comment]
> Related to #64

Yes, the TF<2.5 req is from #64, but that in turn was only necessary to protect the older h5py<3 from becoming dysfunctional when TF 2.5 was released.

At the time, I did not know that Calamari 1.0 models were in fact compatible with h5py 3 on TF 2.5 – I just assumed your restriction must have been the result of a diagnosis to the contrary (and I did see similar incompatibilities elsewhere).

But 15bcfde180975f8cbf6ffc58bca0a172718f34e1's changelog hints that this was just transient: TF 2.4 _itself at the time_ was not compatible with h5py 3. 

So unless I am missing something the solution to this – as well as to [ocrd_all conflicts](https://github.com/OCR-D/ocrd_calamari/commit/2fd6e536f6bf83975ba09353a83e04d75e680535#comments) is to just ditch both the maximum h5py and TF restrictions.

**Comment by mikegerber** [comment]
> Yes, the TF<2.5 req is from #64, but that in turn was only necessary to protect the older h5py<3 from becoming dysfunctional 
> But [15bcfde](https://github.com/OCR-D/ocrd_calamari/commit/15bcfde180975f8cbf6ffc58bca0a172718f34e1)'s changelog hints that this was just transient: TF 2.4 _itself at the time_ was not compatible with h5py 3.

That was the usual dance around shortcomings of pip, i.e. install compatible versions of TF and h5py. I'll commit a fix that seems to work for Python 3.6 and Python 3.9!

**Comment by mikegerber** [comment]
This comes up again with #61 - Calamari 2.1 depends on TF 2.4.x, which is not PyPI-available for Python >= 3.9... Great joy!

**Comment by mikegerber** [comment]
https://github.com/Calamari-OCR/calamari/issues/304

**Comment by mikegerber** [comment]
This is not an issue at the moment, but might come up again with Calamari 2.
