### ISSUE TITLE
Does ocrd_calamari use GPU using ocrd/all:maximum-cuda image?

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_calamari#68]
Reported by @jbarth-ubhd in Gitter (Oct 06 10:50)
> calamari-recognize does not run on GPU, even with maximum-cuda

This seems to be concluded from this memory usage graph:

![image](https://user-images.githubusercontent.com/34309482/136823939-0a823ba0-6b1d-40f3-b80c-09b257f5ae54.png)
gpu memory usage, red=sbb-binarize, blue=eynollah-segment, green=calamari-recognize

**Comment by maxnth** [comment]
I can't comment on whether ocrd_calamari actually leverages the GPU or not but AFAIK calamari should seldomly put heavy load on the GPU during recognition anyways.
